# Generated by Django 5.2.5 on 2025-09-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_mymodelname_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Eglish', max_length=70, verbose_name='Language'),
        ),
    ]
